### ISSUE TITLE
Form se corre a la izquierda cuando esta en mobile y separación de secciones.

### ISSUE THREAD

**Issue by FacundoEG** [heberjbaez/desafio-m3#1]
Hola Heber! primero que todo te felicito por la page, quedo muy prolija! 

Te comento algo que note cuando paso la resolución a modo mobile, veo que el contenido dentro de "form-container" se corre para la izquierda. 

![image](https://user-images.githubusercontent.com/79592789/125821335-7685b656-2cb0-4808-ad5c-295924c803ec.png)

Es algo re mínimo, pero se puede solucionar fácilmente quitándole la propiedad "align-self: flex-start" cuando esta en modo mobile y dejársela cuando pasa a desktop.

Ademas te recomiendo que revises el margen de "title-services" ya que me parece que te esta empujando el contenedor de arriba, note que hay un espacio entre las secciones about y services.

![image](https://user-images.githubusercontent.com/79592789/125823287-622cb06f-937f-4900-899d-cddd53c90d01.png)

Sacando eso no encontré otra cosa, por el resto te felicito porque quedo muy ordenado.

Te mando saludos!

**Comment by heberjbaez** [comment]
Hola Facu! gracias por el feedback. Ya corregí los puntos que me marcaste.

Saludos!
